import type { paths } from "@/schema" // generated by openapi-typescript

export type { paths }

export type GetProductsSuccessResponse =
  paths["/products"]["get"]["responses"][200]["content"]["application/json"]
